### ISSUE TITLE
Is send_nsca working on windows?

### ISSUE THREAD

**Issue by marianrabagel** [NagiosEnterprises/nsca#29]
Hello,

This is not an issue, but a question. 
Is send_nsca working on windows? 

Thanks.

**Comment by box293** [comment]
I've not used it myself however I would personally suggest moving to using NRDP and NCPA to send the passive check results.

This document explains it all:

https://assets.nagios.com/downloads/ncpa/docs/Using-NCPA-For-Passive-Checks.pdf

The main reason why I suggest NRDP instead of NSCA is that it it less complicated, all the security and encryption is handled by Apache.

**Comment by marianrabagel** [comment]
I will have a look.

Thanks a lot.

Later edit:
I managed to make it work on windows by using an already compiled send_nsca form exchange.nagios.org
